// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ServidorUsuarios.proto

/*
Package ServidorUsuarios is a generated protocol buffer package.

It is generated from these files:
	ServidorUsuarios.proto

It has these top-level messages:
	RegistroUsuario
	UsuarioResponse
	ModoBusca
	Resultado
*/
package ServidorUsuarios

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModoBusca_Modo int32

const (
	ModoBusca_NOME  ModoBusca_Modo = 0
	ModoBusca_ID    ModoBusca_Modo = 1
	ModoBusca_TODOS ModoBusca_Modo = 2
)

var ModoBusca_Modo_name = map[int32]string{
	0: "NOME",
	1: "ID",
	2: "TODOS",
}
var ModoBusca_Modo_value = map[string]int32{
	"NOME":  0,
	"ID":    1,
	"TODOS": 2,
}

func (x ModoBusca_Modo) String() string {
	return proto.EnumName(ModoBusca_Modo_name, int32(x))
}
func (ModoBusca_Modo) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type RegistroUsuario struct {
	Id    int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Login string `protobuf:"bytes,2,opt,name=login" json:"login,omitempty"`
	Senha string `protobuf:"bytes,3,opt,name=senha" json:"senha,omitempty"`
}

func (m *RegistroUsuario) Reset()                    { *m = RegistroUsuario{} }
func (m *RegistroUsuario) String() string            { return proto.CompactTextString(m) }
func (*RegistroUsuario) ProtoMessage()               {}
func (*RegistroUsuario) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegistroUsuario) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegistroUsuario) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

func (m *RegistroUsuario) GetSenha() string {
	if m != nil {
		return m.Senha
	}
	return ""
}

type UsuarioResponse struct {
	Message  string           `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Rusuario *RegistroUsuario `protobuf:"bytes,2,opt,name=rusuario" json:"rusuario,omitempty"`
	Error    int32            `protobuf:"varint,3,opt,name=error" json:"error,omitempty"`
}

func (m *UsuarioResponse) Reset()                    { *m = UsuarioResponse{} }
func (m *UsuarioResponse) String() string            { return proto.CompactTextString(m) }
func (*UsuarioResponse) ProtoMessage()               {}
func (*UsuarioResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UsuarioResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UsuarioResponse) GetRusuario() *RegistroUsuario {
	if m != nil {
		return m.Rusuario
	}
	return nil
}

func (m *UsuarioResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type ModoBusca struct {
	Tipo  ModoBusca_Modo `protobuf:"varint,1,opt,name=tipo,enum=ServidorUsuarios.ModoBusca_Modo" json:"tipo,omitempty"`
	Id    int32          `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Login string         `protobuf:"bytes,3,opt,name=login" json:"login,omitempty"`
}

func (m *ModoBusca) Reset()                    { *m = ModoBusca{} }
func (m *ModoBusca) String() string            { return proto.CompactTextString(m) }
func (*ModoBusca) ProtoMessage()               {}
func (*ModoBusca) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ModoBusca) GetTipo() ModoBusca_Modo {
	if m != nil {
		return m.Tipo
	}
	return ModoBusca_NOME
}

func (m *ModoBusca) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModoBusca) GetLogin() string {
	if m != nil {
		return m.Login
	}
	return ""
}

type Resultado struct {
	Usuarios []*RegistroUsuario `protobuf:"bytes,1,rep,name=usuarios" json:"usuarios,omitempty"`
	Message  *UsuarioResponse   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Resultado) Reset()                    { *m = Resultado{} }
func (m *Resultado) String() string            { return proto.CompactTextString(m) }
func (*Resultado) ProtoMessage()               {}
func (*Resultado) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Resultado) GetUsuarios() []*RegistroUsuario {
	if m != nil {
		return m.Usuarios
	}
	return nil
}

func (m *Resultado) GetMessage() *UsuarioResponse {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*RegistroUsuario)(nil), "ServidorUsuarios.RegistroUsuario")
	proto.RegisterType((*UsuarioResponse)(nil), "ServidorUsuarios.UsuarioResponse")
	proto.RegisterType((*ModoBusca)(nil), "ServidorUsuarios.ModoBusca")
	proto.RegisterType((*Resultado)(nil), "ServidorUsuarios.Resultado")
	proto.RegisterEnum("ServidorUsuarios.ModoBusca_Modo", ModoBusca_Modo_name, ModoBusca_Modo_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Usuarios service

type UsuariosClient interface {
	Salvar(ctx context.Context, in *RegistroUsuario, opts ...grpc.CallOption) (*UsuarioResponse, error)
	Buscar(ctx context.Context, in *ModoBusca, opts ...grpc.CallOption) (*Resultado, error)
	Excluir(ctx context.Context, in *RegistroUsuario, opts ...grpc.CallOption) (*UsuarioResponse, error)
}

type usuariosClient struct {
	cc *grpc.ClientConn
}

func NewUsuariosClient(cc *grpc.ClientConn) UsuariosClient {
	return &usuariosClient{cc}
}

func (c *usuariosClient) Salvar(ctx context.Context, in *RegistroUsuario, opts ...grpc.CallOption) (*UsuarioResponse, error) {
	out := new(UsuarioResponse)
	err := grpc.Invoke(ctx, "/ServidorUsuarios.Usuarios/Salvar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosClient) Buscar(ctx context.Context, in *ModoBusca, opts ...grpc.CallOption) (*Resultado, error) {
	out := new(Resultado)
	err := grpc.Invoke(ctx, "/ServidorUsuarios.Usuarios/Buscar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usuariosClient) Excluir(ctx context.Context, in *RegistroUsuario, opts ...grpc.CallOption) (*UsuarioResponse, error) {
	out := new(UsuarioResponse)
	err := grpc.Invoke(ctx, "/ServidorUsuarios.Usuarios/Excluir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Usuarios service

type UsuariosServer interface {
	Salvar(context.Context, *RegistroUsuario) (*UsuarioResponse, error)
	Buscar(context.Context, *ModoBusca) (*Resultado, error)
	Excluir(context.Context, *RegistroUsuario) (*UsuarioResponse, error)
}

func RegisterUsuariosServer(s *grpc.Server, srv UsuariosServer) {
	s.RegisterService(&_Usuarios_serviceDesc, srv)
}

func _Usuarios_Salvar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistroUsuario)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).Salvar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServidorUsuarios.Usuarios/Salvar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).Salvar(ctx, req.(*RegistroUsuario))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usuarios_Buscar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModoBusca)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).Buscar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServidorUsuarios.Usuarios/Buscar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).Buscar(ctx, req.(*ModoBusca))
	}
	return interceptor(ctx, in, info, handler)
}

func _Usuarios_Excluir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistroUsuario)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsuariosServer).Excluir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServidorUsuarios.Usuarios/Excluir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsuariosServer).Excluir(ctx, req.(*RegistroUsuario))
	}
	return interceptor(ctx, in, info, handler)
}

var _Usuarios_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ServidorUsuarios.Usuarios",
	HandlerType: (*UsuariosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Salvar",
			Handler:    _Usuarios_Salvar_Handler,
		},
		{
			MethodName: "Buscar",
			Handler:    _Usuarios_Buscar_Handler,
		},
		{
			MethodName: "Excluir",
			Handler:    _Usuarios_Excluir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ServidorUsuarios.proto",
}

func init() { proto.RegisterFile("ServidorUsuarios.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 347 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0xb1, 0x4f, 0xc2, 0x40,
	0x14, 0xc6, 0xb9, 0x42, 0x0b, 0x7d, 0x26, 0xd0, 0xbc, 0x18, 0xd3, 0xc0, 0x52, 0xcf, 0x85, 0x89,
	0x01, 0xdd, 0x8c, 0x8b, 0x81, 0xc1, 0x01, 0xd1, 0x43, 0xff, 0x80, 0x93, 0x5e, 0xf0, 0x92, 0xca,
	0x91, 0xbb, 0x96, 0x38, 0xba, 0xb9, 0xf8, 0xef, 0xba, 0x9b, 0x5e, 0x0b, 0x1a, 0xaa, 0xe2, 0xe0,
	0xd6, 0xf7, 0xe5, 0x7b, 0xdf, 0xfb, 0xee, 0x97, 0xc2, 0xd1, 0x4c, 0xe8, 0xb5, 0x8c, 0x95, 0xbe,
	0x37, 0x19, 0xd7, 0x52, 0x99, 0xc1, 0x4a, 0xab, 0x54, 0x61, 0xb0, 0xab, 0xd3, 0x09, 0x74, 0x98,
	0x58, 0x48, 0x93, 0x6a, 0x55, 0x6a, 0xd8, 0x06, 0x47, 0xc6, 0x21, 0x89, 0x48, 0xdf, 0x65, 0x8e,
	0x8c, 0xf1, 0x10, 0xdc, 0x44, 0x2d, 0xe4, 0x32, 0x74, 0x22, 0xd2, 0xf7, 0x59, 0x31, 0xe4, 0xaa,
	0x11, 0xcb, 0x47, 0x1e, 0xd6, 0x0b, 0xd5, 0x0e, 0xf4, 0x85, 0x40, 0xa7, 0xcc, 0x61, 0xc2, 0xac,
	0xd4, 0xd2, 0x08, 0x0c, 0xa1, 0xf9, 0x24, 0x8c, 0xe1, 0x0b, 0x61, 0x43, 0x7d, 0xb6, 0x19, 0xf1,
	0x02, 0x5a, 0x3a, 0x2b, 0xdc, 0x36, 0xfc, 0x60, 0x78, 0x3c, 0xa8, 0x34, 0xdf, 0xa9, 0xc7, 0xb6,
	0x2b, 0x79, 0x05, 0xa1, 0xb5, 0xd2, 0xb6, 0x82, 0xcb, 0x8a, 0x81, 0xbe, 0x11, 0xf0, 0x27, 0x2a,
	0x56, 0x97, 0x99, 0x99, 0x73, 0x3c, 0x83, 0x46, 0x2a, 0x57, 0xca, 0x5e, 0x6e, 0x0f, 0xa3, 0x6a,
	0xfc, 0xd6, 0x6a, 0xbf, 0x98, 0x75, 0x97, 0x08, 0x9c, 0x2a, 0x82, 0xfa, 0x17, 0x04, 0xf4, 0x04,
	0x1a, 0xf9, 0x0e, 0xb6, 0xa0, 0x71, 0x3d, 0x9d, 0x8c, 0x83, 0x1a, 0x7a, 0xe0, 0x5c, 0x8d, 0x02,
	0x82, 0x3e, 0xb8, 0x77, 0xd3, 0xd1, 0x74, 0x16, 0x38, 0xf4, 0x95, 0x80, 0xcf, 0x84, 0xc9, 0x92,
	0x94, 0xc7, 0x2a, 0x7f, 0x71, 0xd9, 0xde, 0x84, 0x24, 0xaa, 0xff, 0xf1, 0xc5, 0x9b, 0x15, 0x3c,
	0xff, 0x44, 0xf9, 0x23, 0xaf, 0x1d, 0xfc, 0x5b, 0xda, 0xc3, 0x77, 0x02, 0xad, 0x8d, 0x0b, 0x6f,
	0xc0, 0x9b, 0xf1, 0x64, 0xcd, 0x35, 0xee, 0x2f, 0xd0, 0xdd, 0x7f, 0x85, 0xd6, 0x70, 0x04, 0x9e,
	0xe5, 0xa8, 0xb1, 0xf7, 0x0b, 0xe5, 0x6e, 0xef, 0xbb, 0x73, 0x25, 0x1e, 0x5a, 0xc3, 0x5b, 0x68,
	0x8e, 0x9f, 0xe7, 0x49, 0x26, 0xff, 0xad, 0xd8, 0x83, 0x67, 0xff, 0xfd, 0xd3, 0x8f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x14, 0x59, 0x81, 0xcd, 0x15, 0x03, 0x00, 0x00,
}
