// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServidorClientes.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ServidorClientes {

  /// <summary>Holder for reflection information generated from ServidorClientes.proto</summary>
  public static partial class ServidorClientesReflection {

    #region Descriptor
    /// <summary>File descriptor for ServidorClientes.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServidorClientesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZTZXJ2aWRvckNsaWVudGVzLnByb3RvEhBTZXJ2aWRvckNsaWVudGVzImIK",
            "D1JlZ2lzdHJvQ2xpZW50ZRIKCgJpZBgBIAEoBRIMCgRub21lGAIgASgJEg0K",
            "BWVtYWlsGAMgASgJEhAKCHRlbGVmb25lGAQgASgJEhQKDGRhdGFDYWRhc3Ry",
            "bxgFIAEoCSIxCg9DbGllbnRlUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCRIN",
            "CgVlcnJvchgCIAEoBSJ6CglNb2RvQnVzY2ESLgoEdGlwbxgBIAEoDjIgLlNl",
            "cnZpZG9yQ2xpZW50ZXMuTW9kb0J1c2NhLk1vZG8SCgoCaWQYAiABKAUSDAoE",
            "bm9tZRgDIAEoCSIjCgRNb2RvEggKBE5PTUUQABIGCgJJRBABEgkKBVRPRE9T",
            "EAIidAoJUmVzdWx0YWRvEjMKCGNsaWVudGVzGAEgAygLMiEuU2Vydmlkb3JD",
            "bGllbnRlcy5SZWdpc3Ryb0NsaWVudGUSMgoHbWVzc2FnZRgCIAEoCzIhLlNl",
            "cnZpZG9yQ2xpZW50ZXMuQ2xpZW50ZVJlc3BvbnNlMqIBCghDbGllbnRlcxJQ",
            "CgZTYWx2YXISIS5TZXJ2aWRvckNsaWVudGVzLlJlZ2lzdHJvQ2xpZW50ZRoh",
            "LlNlcnZpZG9yQ2xpZW50ZXMuQ2xpZW50ZVJlc3BvbnNlIgASRAoGQnVzY2Fy",
            "EhsuU2Vydmlkb3JDbGllbnRlcy5Nb2RvQnVzY2EaGy5TZXJ2aWRvckNsaWVu",
            "dGVzLlJlc3VsdGFkbyIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorClientes.RegistroCliente), global::ServidorClientes.RegistroCliente.Parser, new[]{ "Id", "Nome", "Email", "Telefone", "DataCadastro" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorClientes.ClienteResponse), global::ServidorClientes.ClienteResponse.Parser, new[]{ "Message", "Error" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorClientes.ModoBusca), global::ServidorClientes.ModoBusca.Parser, new[]{ "Tipo", "Id", "Nome" }, null, new[]{ typeof(global::ServidorClientes.ModoBusca.Types.Modo) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorClientes.Resultado), global::ServidorClientes.Resultado.Parser, new[]{ "Clientes", "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RegistroCliente : pb::IMessage<RegistroCliente> {
    private static readonly pb::MessageParser<RegistroCliente> _parser = new pb::MessageParser<RegistroCliente>(() => new RegistroCliente());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegistroCliente> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorClientes.ServidorClientesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroCliente() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroCliente(RegistroCliente other) : this() {
      id_ = other.id_;
      nome_ = other.nome_;
      email_ = other.email_;
      telefone_ = other.telefone_;
      dataCadastro_ = other.dataCadastro_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroCliente Clone() {
      return new RegistroCliente(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nome" field.</summary>
    public const int NomeFieldNumber = 2;
    private string nome_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nome {
      get { return nome_; }
      set {
        nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 3;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "telefone" field.</summary>
    public const int TelefoneFieldNumber = 4;
    private string telefone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Telefone {
      get { return telefone_; }
      set {
        telefone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dataCadastro" field.</summary>
    public const int DataCadastroFieldNumber = 5;
    private string dataCadastro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DataCadastro {
      get { return dataCadastro_; }
      set {
        dataCadastro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegistroCliente);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegistroCliente other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nome != other.Nome) return false;
      if (Email != other.Email) return false;
      if (Telefone != other.Telefone) return false;
      if (DataCadastro != other.DataCadastro) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Nome.Length != 0) hash ^= Nome.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Telefone.Length != 0) hash ^= Telefone.GetHashCode();
      if (DataCadastro.Length != 0) hash ^= DataCadastro.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nome);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Email);
      }
      if (Telefone.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Telefone);
      }
      if (DataCadastro.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(DataCadastro);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Nome.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Telefone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Telefone);
      }
      if (DataCadastro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DataCadastro);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegistroCliente other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Nome.Length != 0) {
        Nome = other.Nome;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Telefone.Length != 0) {
        Telefone = other.Telefone;
      }
      if (other.DataCadastro.Length != 0) {
        DataCadastro = other.DataCadastro;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Nome = input.ReadString();
            break;
          }
          case 26: {
            Email = input.ReadString();
            break;
          }
          case 34: {
            Telefone = input.ReadString();
            break;
          }
          case 42: {
            DataCadastro = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ClienteResponse : pb::IMessage<ClienteResponse> {
    private static readonly pb::MessageParser<ClienteResponse> _parser = new pb::MessageParser<ClienteResponse>(() => new ClienteResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ClienteResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorClientes.ServidorClientesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClienteResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClienteResponse(ClienteResponse other) : this() {
      message_ = other.message_;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ClienteResponse Clone() {
      return new ClienteResponse(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 2;
    private int error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ClienteResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ClienteResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Error != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (Error != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Error != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ClienteResponse other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Error != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 16: {
            Error = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ModoBusca : pb::IMessage<ModoBusca> {
    private static readonly pb::MessageParser<ModoBusca> _parser = new pb::MessageParser<ModoBusca>(() => new ModoBusca());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ModoBusca> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorClientes.ServidorClientesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca(ModoBusca other) : this() {
      tipo_ = other.tipo_;
      id_ = other.id_;
      nome_ = other.nome_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca Clone() {
      return new ModoBusca(this);
    }

    /// <summary>Field number for the "tipo" field.</summary>
    public const int TipoFieldNumber = 1;
    private global::ServidorClientes.ModoBusca.Types.Modo tipo_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorClientes.ModoBusca.Types.Modo Tipo {
      get { return tipo_; }
      set {
        tipo_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nome" field.</summary>
    public const int NomeFieldNumber = 3;
    private string nome_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nome {
      get { return nome_; }
      set {
        nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ModoBusca);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ModoBusca other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Tipo != other.Tipo) return false;
      if (Id != other.Id) return false;
      if (Nome != other.Nome) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Tipo != 0) hash ^= Tipo.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Nome.Length != 0) hash ^= Nome.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Tipo != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Tipo);
      }
      if (Id != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Id);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nome);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Tipo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Tipo);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Nome.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ModoBusca other) {
      if (other == null) {
        return;
      }
      if (other.Tipo != 0) {
        Tipo = other.Tipo;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Nome.Length != 0) {
        Nome = other.Nome;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            tipo_ = (global::ServidorClientes.ModoBusca.Types.Modo) input.ReadEnum();
            break;
          }
          case 16: {
            Id = input.ReadInt32();
            break;
          }
          case 26: {
            Nome = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ModoBusca message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Modo {
        [pbr::OriginalName("NOME")] Nome = 0,
        [pbr::OriginalName("ID")] Id = 1,
        [pbr::OriginalName("TODOS")] Todos = 2,
      }

    }
    #endregion

  }

  public sealed partial class Resultado : pb::IMessage<Resultado> {
    private static readonly pb::MessageParser<Resultado> _parser = new pb::MessageParser<Resultado>(() => new Resultado());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resultado> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorClientes.ServidorClientesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado(Resultado other) : this() {
      clientes_ = other.clientes_.Clone();
      message_ = other.message_ != null ? other.message_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado Clone() {
      return new Resultado(this);
    }

    /// <summary>Field number for the "clientes" field.</summary>
    public const int ClientesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ServidorClientes.RegistroCliente> _repeated_clientes_codec
        = pb::FieldCodec.ForMessage(10, global::ServidorClientes.RegistroCliente.Parser);
    private readonly pbc::RepeatedField<global::ServidorClientes.RegistroCliente> clientes_ = new pbc::RepeatedField<global::ServidorClientes.RegistroCliente>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ServidorClientes.RegistroCliente> Clientes {
      get { return clientes_; }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private global::ServidorClientes.ClienteResponse message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorClientes.ClienteResponse Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resultado);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resultado other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!clientes_.Equals(other.clientes_)) return false;
      if (!object.Equals(Message, other.Message)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= clientes_.GetHashCode();
      if (message_ != null) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      clientes_.WriteTo(output, _repeated_clientes_codec);
      if (message_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += clientes_.CalculateSize(_repeated_clientes_codec);
      if (message_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resultado other) {
      if (other == null) {
        return;
      }
      clientes_.Add(other.clientes_);
      if (other.message_ != null) {
        if (message_ == null) {
          message_ = new global::ServidorClientes.ClienteResponse();
        }
        Message.MergeFrom(other.Message);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            clientes_.AddEntriesFrom(input, _repeated_clientes_codec);
            break;
          }
          case 18: {
            if (message_ == null) {
              message_ = new global::ServidorClientes.ClienteResponse();
            }
            input.ReadMessage(message_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
