// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServidorClientes.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ServidorClientes {
  public static partial class Clientes
  {
    static readonly string __ServiceName = "ServidorClientes.Clientes";

    static readonly grpc::Marshaller<global::ServidorClientes.RegistroCliente> __Marshaller_ServidorClientes_RegistroCliente = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorClientes.RegistroCliente.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorClientes.ClienteResponse> __Marshaller_ServidorClientes_ClienteResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorClientes.ClienteResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorClientes.ModoBusca> __Marshaller_ServidorClientes_ModoBusca = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorClientes.ModoBusca.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorClientes.Resultado> __Marshaller_ServidorClientes_Resultado = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorClientes.Resultado.Parser.ParseFrom);

    static readonly grpc::Method<global::ServidorClientes.RegistroCliente, global::ServidorClientes.ClienteResponse> __Method_Salvar = new grpc::Method<global::ServidorClientes.RegistroCliente, global::ServidorClientes.ClienteResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Salvar",
        __Marshaller_ServidorClientes_RegistroCliente,
        __Marshaller_ServidorClientes_ClienteResponse);

    static readonly grpc::Method<global::ServidorClientes.ModoBusca, global::ServidorClientes.Resultado> __Method_Buscar = new grpc::Method<global::ServidorClientes.ModoBusca, global::ServidorClientes.Resultado>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Buscar",
        __Marshaller_ServidorClientes_ModoBusca,
        __Marshaller_ServidorClientes_Resultado);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ServidorClientes.ServidorClientesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Clientes</summary>
    public abstract partial class ClientesBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ServidorClientes.ClienteResponse> Salvar(global::ServidorClientes.RegistroCliente request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ServidorClientes.Resultado> Buscar(global::ServidorClientes.ModoBusca request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Clientes</summary>
    public partial class ClientesClient : grpc::ClientBase<ClientesClient>
    {
      /// <summary>Creates a new client for Clientes</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ClientesClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Clientes that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ClientesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ClientesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ClientesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ServidorClientes.ClienteResponse Salvar(global::ServidorClientes.RegistroCliente request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Salvar(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorClientes.ClienteResponse Salvar(global::ServidorClientes.RegistroCliente request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Salvar, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorClientes.ClienteResponse> SalvarAsync(global::ServidorClientes.RegistroCliente request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SalvarAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorClientes.ClienteResponse> SalvarAsync(global::ServidorClientes.RegistroCliente request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Salvar, null, options, request);
      }
      public virtual global::ServidorClientes.Resultado Buscar(global::ServidorClientes.ModoBusca request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Buscar(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorClientes.Resultado Buscar(global::ServidorClientes.ModoBusca request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Buscar, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorClientes.Resultado> BuscarAsync(global::ServidorClientes.ModoBusca request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuscarAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorClientes.Resultado> BuscarAsync(global::ServidorClientes.ModoBusca request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Buscar, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ClientesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ClientesClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ClientesBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Salvar, serviceImpl.Salvar)
          .AddMethod(__Method_Buscar, serviceImpl.Buscar).Build();
    }

  }
}
#endregion
