// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServidorUsuarios.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ServidorUsuarios {

  /// <summary>Holder for reflection information generated from ServidorUsuarios.proto</summary>
  public static partial class ServidorUsuariosReflection {

    #region Descriptor
    /// <summary>File descriptor for ServidorUsuarios.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServidorUsuariosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZTZXJ2aWRvclVzdWFyaW9zLnByb3RvEhBTZXJ2aWRvclVzdWFyaW9zIjsK",
            "D1JlZ2lzdHJvVXN1YXJpbxIKCgJpZBgBIAEoBRINCgVsb2dpbhgCIAEoCRIN",
            "CgVzZW5oYRgDIAEoCSJmCg9Vc3VhcmlvUmVzcG9uc2USDwoHbWVzc2FnZRgB",
            "IAEoCRIzCghydXN1YXJpbxgCIAEoCzIhLlNlcnZpZG9yVXN1YXJpb3MuUmVn",
            "aXN0cm9Vc3VhcmlvEg0KBWVycm9yGAMgASgFInsKCU1vZG9CdXNjYRIuCgR0",
            "aXBvGAEgASgOMiAuU2Vydmlkb3JVc3Vhcmlvcy5Nb2RvQnVzY2EuTW9kbxIK",
            "CgJpZBgCIAEoBRINCgVsb2dpbhgDIAEoCSIjCgRNb2RvEggKBE5PTUUQABIG",
            "CgJJRBABEgkKBVRPRE9TEAIidAoJUmVzdWx0YWRvEjMKCHVzdWFyaW9zGAEg",
            "AygLMiEuU2Vydmlkb3JVc3Vhcmlvcy5SZWdpc3Ryb1VzdWFyaW8SMgoHbWVz",
            "c2FnZRgCIAEoCzIhLlNlcnZpZG9yVXN1YXJpb3MuVXN1YXJpb1Jlc3BvbnNl",
            "MvUBCghVc3VhcmlvcxJQCgZTYWx2YXISIS5TZXJ2aWRvclVzdWFyaW9zLlJl",
            "Z2lzdHJvVXN1YXJpbxohLlNlcnZpZG9yVXN1YXJpb3MuVXN1YXJpb1Jlc3Bv",
            "bnNlIgASRAoGQnVzY2FyEhsuU2Vydmlkb3JVc3Vhcmlvcy5Nb2RvQnVzY2Ea",
            "Gy5TZXJ2aWRvclVzdWFyaW9zLlJlc3VsdGFkbyIAElEKB0V4Y2x1aXISIS5T",
            "ZXJ2aWRvclVzdWFyaW9zLlJlZ2lzdHJvVXN1YXJpbxohLlNlcnZpZG9yVXN1",
            "YXJpb3MuVXN1YXJpb1Jlc3BvbnNlIgBiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorUsuarios.RegistroUsuario), global::ServidorUsuarios.RegistroUsuario.Parser, new[]{ "Id", "Login", "Senha" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorUsuarios.UsuarioResponse), global::ServidorUsuarios.UsuarioResponse.Parser, new[]{ "Message", "Rusuario", "Error" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorUsuarios.ModoBusca), global::ServidorUsuarios.ModoBusca.Parser, new[]{ "Tipo", "Id", "Login" }, null, new[]{ typeof(global::ServidorUsuarios.ModoBusca.Types.Modo) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorUsuarios.Resultado), global::ServidorUsuarios.Resultado.Parser, new[]{ "Usuarios", "Message" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RegistroUsuario : pb::IMessage<RegistroUsuario> {
    private static readonly pb::MessageParser<RegistroUsuario> _parser = new pb::MessageParser<RegistroUsuario>(() => new RegistroUsuario());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegistroUsuario> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorUsuarios.ServidorUsuariosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroUsuario() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroUsuario(RegistroUsuario other) : this() {
      id_ = other.id_;
      login_ = other.login_;
      senha_ = other.senha_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroUsuario Clone() {
      return new RegistroUsuario(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "login" field.</summary>
    public const int LoginFieldNumber = 2;
    private string login_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Login {
      get { return login_; }
      set {
        login_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "senha" field.</summary>
    public const int SenhaFieldNumber = 3;
    private string senha_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Senha {
      get { return senha_; }
      set {
        senha_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegistroUsuario);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegistroUsuario other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Login != other.Login) return false;
      if (Senha != other.Senha) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Login.Length != 0) hash ^= Login.GetHashCode();
      if (Senha.Length != 0) hash ^= Senha.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Login.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Login);
      }
      if (Senha.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Senha);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Login.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Login);
      }
      if (Senha.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Senha);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegistroUsuario other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Login.Length != 0) {
        Login = other.Login;
      }
      if (other.Senha.Length != 0) {
        Senha = other.Senha;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Login = input.ReadString();
            break;
          }
          case 26: {
            Senha = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class UsuarioResponse : pb::IMessage<UsuarioResponse> {
    private static readonly pb::MessageParser<UsuarioResponse> _parser = new pb::MessageParser<UsuarioResponse>(() => new UsuarioResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UsuarioResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorUsuarios.ServidorUsuariosReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsuarioResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsuarioResponse(UsuarioResponse other) : this() {
      message_ = other.message_;
      rusuario_ = other.rusuario_ != null ? other.rusuario_.Clone() : null;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UsuarioResponse Clone() {
      return new UsuarioResponse(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rusuario" field.</summary>
    public const int RusuarioFieldNumber = 2;
    private global::ServidorUsuarios.RegistroUsuario rusuario_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorUsuarios.RegistroUsuario Rusuario {
      get { return rusuario_; }
      set {
        rusuario_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 3;
    private int error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UsuarioResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UsuarioResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      if (!object.Equals(Rusuario, other.Rusuario)) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (rusuario_ != null) hash ^= Rusuario.GetHashCode();
      if (Error != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (rusuario_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Rusuario);
      }
      if (Error != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (rusuario_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rusuario);
      }
      if (Error != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UsuarioResponse other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.rusuario_ != null) {
        if (rusuario_ == null) {
          rusuario_ = new global::ServidorUsuarios.RegistroUsuario();
        }
        Rusuario.MergeFrom(other.Rusuario);
      }
      if (other.Error != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 18: {
            if (rusuario_ == null) {
              rusuario_ = new global::ServidorUsuarios.RegistroUsuario();
            }
            input.ReadMessage(rusuario_);
            break;
          }
          case 24: {
            Error = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ModoBusca : pb::IMessage<ModoBusca> {
    private static readonly pb::MessageParser<ModoBusca> _parser = new pb::MessageParser<ModoBusca>(() => new ModoBusca());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ModoBusca> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorUsuarios.ServidorUsuariosReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca(ModoBusca other) : this() {
      tipo_ = other.tipo_;
      id_ = other.id_;
      login_ = other.login_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca Clone() {
      return new ModoBusca(this);
    }

    /// <summary>Field number for the "tipo" field.</summary>
    public const int TipoFieldNumber = 1;
    private global::ServidorUsuarios.ModoBusca.Types.Modo tipo_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorUsuarios.ModoBusca.Types.Modo Tipo {
      get { return tipo_; }
      set {
        tipo_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "login" field.</summary>
    public const int LoginFieldNumber = 3;
    private string login_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Login {
      get { return login_; }
      set {
        login_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ModoBusca);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ModoBusca other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Tipo != other.Tipo) return false;
      if (Id != other.Id) return false;
      if (Login != other.Login) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Tipo != 0) hash ^= Tipo.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Login.Length != 0) hash ^= Login.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Tipo != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Tipo);
      }
      if (Id != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Id);
      }
      if (Login.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Login);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Tipo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Tipo);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Login.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Login);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ModoBusca other) {
      if (other == null) {
        return;
      }
      if (other.Tipo != 0) {
        Tipo = other.Tipo;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Login.Length != 0) {
        Login = other.Login;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            tipo_ = (global::ServidorUsuarios.ModoBusca.Types.Modo) input.ReadEnum();
            break;
          }
          case 16: {
            Id = input.ReadInt32();
            break;
          }
          case 26: {
            Login = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ModoBusca message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Modo {
        [pbr::OriginalName("NOME")] Nome = 0,
        [pbr::OriginalName("ID")] Id = 1,
        [pbr::OriginalName("TODOS")] Todos = 2,
      }

    }
    #endregion

  }

  public sealed partial class Resultado : pb::IMessage<Resultado> {
    private static readonly pb::MessageParser<Resultado> _parser = new pb::MessageParser<Resultado>(() => new Resultado());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resultado> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorUsuarios.ServidorUsuariosReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado(Resultado other) : this() {
      usuarios_ = other.usuarios_.Clone();
      message_ = other.message_ != null ? other.message_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado Clone() {
      return new Resultado(this);
    }

    /// <summary>Field number for the "usuarios" field.</summary>
    public const int UsuariosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ServidorUsuarios.RegistroUsuario> _repeated_usuarios_codec
        = pb::FieldCodec.ForMessage(10, global::ServidorUsuarios.RegistroUsuario.Parser);
    private readonly pbc::RepeatedField<global::ServidorUsuarios.RegistroUsuario> usuarios_ = new pbc::RepeatedField<global::ServidorUsuarios.RegistroUsuario>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ServidorUsuarios.RegistroUsuario> Usuarios {
      get { return usuarios_; }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private global::ServidorUsuarios.UsuarioResponse message_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorUsuarios.UsuarioResponse Message {
      get { return message_; }
      set {
        message_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resultado);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resultado other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!usuarios_.Equals(other.usuarios_)) return false;
      if (!object.Equals(Message, other.Message)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= usuarios_.GetHashCode();
      if (message_ != null) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      usuarios_.WriteTo(output, _repeated_usuarios_codec);
      if (message_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += usuarios_.CalculateSize(_repeated_usuarios_codec);
      if (message_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resultado other) {
      if (other == null) {
        return;
      }
      usuarios_.Add(other.usuarios_);
      if (other.message_ != null) {
        if (message_ == null) {
          message_ = new global::ServidorUsuarios.UsuarioResponse();
        }
        Message.MergeFrom(other.Message);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            usuarios_.AddEntriesFrom(input, _repeated_usuarios_codec);
            break;
          }
          case 18: {
            if (message_ == null) {
              message_ = new global::ServidorUsuarios.UsuarioResponse();
            }
            input.ReadMessage(message_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
