// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServidorUsuarios.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ServidorUsuarios {
  public static partial class Usuarios
  {
    static readonly string __ServiceName = "ServidorUsuarios.Usuarios";

    static readonly grpc::Marshaller<global::ServidorUsuarios.RegistroUsuario> __Marshaller_ServidorUsuarios_RegistroUsuario = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorUsuarios.RegistroUsuario.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorUsuarios.UsuarioResponse> __Marshaller_ServidorUsuarios_UsuarioResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorUsuarios.UsuarioResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorUsuarios.ModoBusca> __Marshaller_ServidorUsuarios_ModoBusca = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorUsuarios.ModoBusca.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorUsuarios.Resultado> __Marshaller_ServidorUsuarios_Resultado = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorUsuarios.Resultado.Parser.ParseFrom);

    static readonly grpc::Method<global::ServidorUsuarios.RegistroUsuario, global::ServidorUsuarios.UsuarioResponse> __Method_Salvar = new grpc::Method<global::ServidorUsuarios.RegistroUsuario, global::ServidorUsuarios.UsuarioResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Salvar",
        __Marshaller_ServidorUsuarios_RegistroUsuario,
        __Marshaller_ServidorUsuarios_UsuarioResponse);

    static readonly grpc::Method<global::ServidorUsuarios.ModoBusca, global::ServidorUsuarios.Resultado> __Method_Buscar = new grpc::Method<global::ServidorUsuarios.ModoBusca, global::ServidorUsuarios.Resultado>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Buscar",
        __Marshaller_ServidorUsuarios_ModoBusca,
        __Marshaller_ServidorUsuarios_Resultado);

    static readonly grpc::Method<global::ServidorUsuarios.RegistroUsuario, global::ServidorUsuarios.UsuarioResponse> __Method_Excluir = new grpc::Method<global::ServidorUsuarios.RegistroUsuario, global::ServidorUsuarios.UsuarioResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Excluir",
        __Marshaller_ServidorUsuarios_RegistroUsuario,
        __Marshaller_ServidorUsuarios_UsuarioResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ServidorUsuarios.ServidorUsuariosReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Usuarios</summary>
    public abstract partial class UsuariosBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ServidorUsuarios.UsuarioResponse> Salvar(global::ServidorUsuarios.RegistroUsuario request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ServidorUsuarios.Resultado> Buscar(global::ServidorUsuarios.ModoBusca request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ServidorUsuarios.UsuarioResponse> Excluir(global::ServidorUsuarios.RegistroUsuario request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Usuarios</summary>
    public partial class UsuariosClient : grpc::ClientBase<UsuariosClient>
    {
      /// <summary>Creates a new client for Usuarios</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UsuariosClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Usuarios that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UsuariosClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UsuariosClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UsuariosClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ServidorUsuarios.UsuarioResponse Salvar(global::ServidorUsuarios.RegistroUsuario request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Salvar(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorUsuarios.UsuarioResponse Salvar(global::ServidorUsuarios.RegistroUsuario request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Salvar, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorUsuarios.UsuarioResponse> SalvarAsync(global::ServidorUsuarios.RegistroUsuario request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SalvarAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorUsuarios.UsuarioResponse> SalvarAsync(global::ServidorUsuarios.RegistroUsuario request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Salvar, null, options, request);
      }
      public virtual global::ServidorUsuarios.Resultado Buscar(global::ServidorUsuarios.ModoBusca request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Buscar(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorUsuarios.Resultado Buscar(global::ServidorUsuarios.ModoBusca request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Buscar, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorUsuarios.Resultado> BuscarAsync(global::ServidorUsuarios.ModoBusca request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuscarAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorUsuarios.Resultado> BuscarAsync(global::ServidorUsuarios.ModoBusca request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Buscar, null, options, request);
      }
      public virtual global::ServidorUsuarios.UsuarioResponse Excluir(global::ServidorUsuarios.RegistroUsuario request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Excluir(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorUsuarios.UsuarioResponse Excluir(global::ServidorUsuarios.RegistroUsuario request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Excluir, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorUsuarios.UsuarioResponse> ExcluirAsync(global::ServidorUsuarios.RegistroUsuario request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExcluirAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorUsuarios.UsuarioResponse> ExcluirAsync(global::ServidorUsuarios.RegistroUsuario request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Excluir, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UsuariosClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UsuariosClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UsuariosBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Salvar, serviceImpl.Salvar)
          .AddMethod(__Method_Buscar, serviceImpl.Buscar)
          .AddMethod(__Method_Excluir, serviceImpl.Excluir).Build();
    }

  }
}
#endregion
