// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServidorPedidos.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ServidorPedidos {
  public static partial class Pedidos
  {
    static readonly string __ServiceName = "ServidorPedidos.Pedidos";

    static readonly grpc::Marshaller<global::ServidorPedidos.RegistroPedido> __Marshaller_ServidorPedidos_RegistroPedido = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorPedidos.RegistroPedido.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorPedidos.PedidoResponse> __Marshaller_ServidorPedidos_PedidoResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorPedidos.PedidoResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorPedidos.ModoBusca> __Marshaller_ServidorPedidos_ModoBusca = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorPedidos.ModoBusca.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorPedidos.Resultado> __Marshaller_ServidorPedidos_Resultado = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorPedidos.Resultado.Parser.ParseFrom);

    static readonly grpc::Method<global::ServidorPedidos.RegistroPedido, global::ServidorPedidos.PedidoResponse> __Method_Salvar = new grpc::Method<global::ServidorPedidos.RegistroPedido, global::ServidorPedidos.PedidoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Salvar",
        __Marshaller_ServidorPedidos_RegistroPedido,
        __Marshaller_ServidorPedidos_PedidoResponse);

    static readonly grpc::Method<global::ServidorPedidos.ModoBusca, global::ServidorPedidos.Resultado> __Method_Buscar = new grpc::Method<global::ServidorPedidos.ModoBusca, global::ServidorPedidos.Resultado>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Buscar",
        __Marshaller_ServidorPedidos_ModoBusca,
        __Marshaller_ServidorPedidos_Resultado);

    static readonly grpc::Method<global::ServidorPedidos.RegistroPedido, global::ServidorPedidos.PedidoResponse> __Method_Excluir = new grpc::Method<global::ServidorPedidos.RegistroPedido, global::ServidorPedidos.PedidoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Excluir",
        __Marshaller_ServidorPedidos_RegistroPedido,
        __Marshaller_ServidorPedidos_PedidoResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ServidorPedidos.ServidorPedidosReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Pedidos</summary>
    public abstract partial class PedidosBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ServidorPedidos.PedidoResponse> Salvar(global::ServidorPedidos.RegistroPedido request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ServidorPedidos.Resultado> Buscar(global::ServidorPedidos.ModoBusca request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ServidorPedidos.PedidoResponse> Excluir(global::ServidorPedidos.RegistroPedido request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Pedidos</summary>
    public partial class PedidosClient : grpc::ClientBase<PedidosClient>
    {
      /// <summary>Creates a new client for Pedidos</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public PedidosClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Pedidos that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public PedidosClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected PedidosClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected PedidosClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ServidorPedidos.PedidoResponse Salvar(global::ServidorPedidos.RegistroPedido request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Salvar(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorPedidos.PedidoResponse Salvar(global::ServidorPedidos.RegistroPedido request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Salvar, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorPedidos.PedidoResponse> SalvarAsync(global::ServidorPedidos.RegistroPedido request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SalvarAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorPedidos.PedidoResponse> SalvarAsync(global::ServidorPedidos.RegistroPedido request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Salvar, null, options, request);
      }
      public virtual global::ServidorPedidos.Resultado Buscar(global::ServidorPedidos.ModoBusca request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Buscar(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorPedidos.Resultado Buscar(global::ServidorPedidos.ModoBusca request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Buscar, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorPedidos.Resultado> BuscarAsync(global::ServidorPedidos.ModoBusca request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuscarAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorPedidos.Resultado> BuscarAsync(global::ServidorPedidos.ModoBusca request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Buscar, null, options, request);
      }
      public virtual global::ServidorPedidos.PedidoResponse Excluir(global::ServidorPedidos.RegistroPedido request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Excluir(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorPedidos.PedidoResponse Excluir(global::ServidorPedidos.RegistroPedido request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Excluir, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorPedidos.PedidoResponse> ExcluirAsync(global::ServidorPedidos.RegistroPedido request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExcluirAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorPedidos.PedidoResponse> ExcluirAsync(global::ServidorPedidos.RegistroPedido request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Excluir, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override PedidosClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new PedidosClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(PedidosBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Salvar, serviceImpl.Salvar)
          .AddMethod(__Method_Buscar, serviceImpl.Buscar)
          .AddMethod(__Method_Excluir, serviceImpl.Excluir).Build();
    }

  }
}
#endregion
