// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServidorProdutos.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ServidorProdutos {
  public static partial class Produtos
  {
    static readonly string __ServiceName = "ServidorProdutos.Produtos";

    static readonly grpc::Marshaller<global::ServidorProdutos.RegistroProduto> __Marshaller_ServidorProdutos_RegistroProduto = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorProdutos.RegistroProduto.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorProdutos.ProdutoResponse> __Marshaller_ServidorProdutos_ProdutoResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorProdutos.ProdutoResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorProdutos.ModoBusca> __Marshaller_ServidorProdutos_ModoBusca = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorProdutos.ModoBusca.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ServidorProdutos.Resultado> __Marshaller_ServidorProdutos_Resultado = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ServidorProdutos.Resultado.Parser.ParseFrom);

    static readonly grpc::Method<global::ServidorProdutos.RegistroProduto, global::ServidorProdutos.ProdutoResponse> __Method_Salvar = new grpc::Method<global::ServidorProdutos.RegistroProduto, global::ServidorProdutos.ProdutoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Salvar",
        __Marshaller_ServidorProdutos_RegistroProduto,
        __Marshaller_ServidorProdutos_ProdutoResponse);

    static readonly grpc::Method<global::ServidorProdutos.ModoBusca, global::ServidorProdutos.Resultado> __Method_Buscar = new grpc::Method<global::ServidorProdutos.ModoBusca, global::ServidorProdutos.Resultado>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Buscar",
        __Marshaller_ServidorProdutos_ModoBusca,
        __Marshaller_ServidorProdutos_Resultado);

    static readonly grpc::Method<global::ServidorProdutos.RegistroProduto, global::ServidorProdutos.ProdutoResponse> __Method_Excluir = new grpc::Method<global::ServidorProdutos.RegistroProduto, global::ServidorProdutos.ProdutoResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Excluir",
        __Marshaller_ServidorProdutos_RegistroProduto,
        __Marshaller_ServidorProdutos_ProdutoResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ServidorProdutos.ServidorProdutosReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Produtos</summary>
    public abstract partial class ProdutosBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ServidorProdutos.ProdutoResponse> Salvar(global::ServidorProdutos.RegistroProduto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ServidorProdutos.Resultado> Buscar(global::ServidorProdutos.ModoBusca request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ServidorProdutos.ProdutoResponse> Excluir(global::ServidorProdutos.RegistroProduto request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Produtos</summary>
    public partial class ProdutosClient : grpc::ClientBase<ProdutosClient>
    {
      /// <summary>Creates a new client for Produtos</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ProdutosClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Produtos that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ProdutosClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ProdutosClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ProdutosClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ServidorProdutos.ProdutoResponse Salvar(global::ServidorProdutos.RegistroProduto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Salvar(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorProdutos.ProdutoResponse Salvar(global::ServidorProdutos.RegistroProduto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Salvar, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorProdutos.ProdutoResponse> SalvarAsync(global::ServidorProdutos.RegistroProduto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SalvarAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorProdutos.ProdutoResponse> SalvarAsync(global::ServidorProdutos.RegistroProduto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Salvar, null, options, request);
      }
      public virtual global::ServidorProdutos.Resultado Buscar(global::ServidorProdutos.ModoBusca request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Buscar(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorProdutos.Resultado Buscar(global::ServidorProdutos.ModoBusca request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Buscar, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorProdutos.Resultado> BuscarAsync(global::ServidorProdutos.ModoBusca request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BuscarAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorProdutos.Resultado> BuscarAsync(global::ServidorProdutos.ModoBusca request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Buscar, null, options, request);
      }
      public virtual global::ServidorProdutos.ProdutoResponse Excluir(global::ServidorProdutos.RegistroProduto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Excluir(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ServidorProdutos.ProdutoResponse Excluir(global::ServidorProdutos.RegistroProduto request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Excluir, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorProdutos.ProdutoResponse> ExcluirAsync(global::ServidorProdutos.RegistroProduto request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExcluirAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ServidorProdutos.ProdutoResponse> ExcluirAsync(global::ServidorProdutos.RegistroProduto request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Excluir, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ProdutosClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ProdutosClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ProdutosBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Salvar, serviceImpl.Salvar)
          .AddMethod(__Method_Buscar, serviceImpl.Buscar)
          .AddMethod(__Method_Excluir, serviceImpl.Excluir).Build();
    }

  }
}
#endregion
