// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServidorPedidos.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ServidorPedidos {

  /// <summary>Holder for reflection information generated from ServidorPedidos.proto</summary>
  public static partial class ServidorPedidosReflection {

    #region Descriptor
    /// <summary>File descriptor for ServidorPedidos.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServidorPedidosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVTZXJ2aWRvclBlZGlkb3MucHJvdG8SD1NlcnZpZG9yUGVkaWRvcyJKCgtQ",
            "cm9kdXRvSXRlbRIRCglpZFByb2R1dG8YASABKAUSCwoDcXRkGAIgASgFEg0K",
            "BXZhbG9yGAMgASgBEgwKBG5vbWUYBCABKAkiywEKDlJlZ2lzdHJvUGVkaWRv",
            "EgoKAmlkGAEgASgFEhMKC2RhdGFFbnRyYWRhGAIgASgJEhMKC2RhdGFFbnRy",
            "ZWdhGAMgASgJEhAKCGVuZGVyZWNvGAQgASgJEhAKCHRlbGVmb25lGAUgASgJ",
            "Eg0KBWVtYWlsGAYgASgJEhIKCm9ic2VydmFjYW8YByABKAkSDwoHY2xpZW50",
            "ZRgIIAEoCRIrCgVpdGVucxgJIAMoCzIcLlNlcnZpZG9yUGVkaWRvcy5Qcm9k",
            "dXRvSXRlbSJhCg5QZWRpZG9SZXNwb25zZRIvCgZwZWRpZG8YASABKAsyHy5T",
            "ZXJ2aWRvclBlZGlkb3MuUmVnaXN0cm9QZWRpZG8SDwoHbWVzc2FnZRgCIAEo",
            "CRINCgVlcnJvchgDIAEoBSJ5CglNb2RvQnVzY2ESLQoEdGlwbxgBIAEoDjIf",
            "LlNlcnZpZG9yUGVkaWRvcy5Nb2RvQnVzY2EuTW9kbxIKCgJpZBgCIAEoBRIM",
            "CgRub21lGAMgASgJIiMKBE1vZG8SCAoETk9NRRAAEgYKAklEEAESCQoFVE9E",
            "T1MQAiJwCglSZXN1bHRhZG8SMAoHcGVkaWRvcxgBIAMoCzIfLlNlcnZpZG9y",
            "UGVkaWRvcy5SZWdpc3Ryb1BlZGlkbxIxCghyZXNwb25zZRgCIAEoCzIfLlNl",
            "cnZpZG9yUGVkaWRvcy5QZWRpZG9SZXNwb25zZTLqAQoHUGVkaWRvcxJMCgZT",
            "YWx2YXISHy5TZXJ2aWRvclBlZGlkb3MuUmVnaXN0cm9QZWRpZG8aHy5TZXJ2",
            "aWRvclBlZGlkb3MuUGVkaWRvUmVzcG9uc2UiABJCCgZCdXNjYXISGi5TZXJ2",
            "aWRvclBlZGlkb3MuTW9kb0J1c2NhGhouU2Vydmlkb3JQZWRpZG9zLlJlc3Vs",
            "dGFkbyIAEk0KB0V4Y2x1aXISHy5TZXJ2aWRvclBlZGlkb3MuUmVnaXN0cm9Q",
            "ZWRpZG8aHy5TZXJ2aWRvclBlZGlkb3MuUGVkaWRvUmVzcG9uc2UiAGIGcHJv",
            "dG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorPedidos.ProdutoItem), global::ServidorPedidos.ProdutoItem.Parser, new[]{ "IdProduto", "Qtd", "Valor", "Nome" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorPedidos.RegistroPedido), global::ServidorPedidos.RegistroPedido.Parser, new[]{ "Id", "DataEntrada", "DataEntrega", "Endereco", "Telefone", "Email", "Observacao", "Cliente", "Itens" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorPedidos.PedidoResponse), global::ServidorPedidos.PedidoResponse.Parser, new[]{ "Pedido", "Message", "Error" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorPedidos.ModoBusca), global::ServidorPedidos.ModoBusca.Parser, new[]{ "Tipo", "Id", "Nome" }, null, new[]{ typeof(global::ServidorPedidos.ModoBusca.Types.Modo) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorPedidos.Resultado), global::ServidorPedidos.Resultado.Parser, new[]{ "Pedidos", "Response" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ProdutoItem : pb::IMessage<ProdutoItem> {
    private static readonly pb::MessageParser<ProdutoItem> _parser = new pb::MessageParser<ProdutoItem>(() => new ProdutoItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProdutoItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorPedidos.ServidorPedidosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProdutoItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProdutoItem(ProdutoItem other) : this() {
      idProduto_ = other.idProduto_;
      qtd_ = other.qtd_;
      valor_ = other.valor_;
      nome_ = other.nome_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProdutoItem Clone() {
      return new ProdutoItem(this);
    }

    /// <summary>Field number for the "idProduto" field.</summary>
    public const int IdProdutoFieldNumber = 1;
    private int idProduto_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int IdProduto {
      get { return idProduto_; }
      set {
        idProduto_ = value;
      }
    }

    /// <summary>Field number for the "qtd" field.</summary>
    public const int QtdFieldNumber = 2;
    private int qtd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Qtd {
      get { return qtd_; }
      set {
        qtd_ = value;
      }
    }

    /// <summary>Field number for the "valor" field.</summary>
    public const int ValorFieldNumber = 3;
    private double valor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Valor {
      get { return valor_; }
      set {
        valor_ = value;
      }
    }

    /// <summary>Field number for the "nome" field.</summary>
    public const int NomeFieldNumber = 4;
    private string nome_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nome {
      get { return nome_; }
      set {
        nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProdutoItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProdutoItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (IdProduto != other.IdProduto) return false;
      if (Qtd != other.Qtd) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Valor, other.Valor)) return false;
      if (Nome != other.Nome) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (IdProduto != 0) hash ^= IdProduto.GetHashCode();
      if (Qtd != 0) hash ^= Qtd.GetHashCode();
      if (Valor != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Valor);
      if (Nome.Length != 0) hash ^= Nome.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (IdProduto != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(IdProduto);
      }
      if (Qtd != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Qtd);
      }
      if (Valor != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(Valor);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Nome);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (IdProduto != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(IdProduto);
      }
      if (Qtd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Qtd);
      }
      if (Valor != 0D) {
        size += 1 + 8;
      }
      if (Nome.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProdutoItem other) {
      if (other == null) {
        return;
      }
      if (other.IdProduto != 0) {
        IdProduto = other.IdProduto;
      }
      if (other.Qtd != 0) {
        Qtd = other.Qtd;
      }
      if (other.Valor != 0D) {
        Valor = other.Valor;
      }
      if (other.Nome.Length != 0) {
        Nome = other.Nome;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IdProduto = input.ReadInt32();
            break;
          }
          case 16: {
            Qtd = input.ReadInt32();
            break;
          }
          case 25: {
            Valor = input.ReadDouble();
            break;
          }
          case 34: {
            Nome = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class RegistroPedido : pb::IMessage<RegistroPedido> {
    private static readonly pb::MessageParser<RegistroPedido> _parser = new pb::MessageParser<RegistroPedido>(() => new RegistroPedido());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegistroPedido> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorPedidos.ServidorPedidosReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroPedido() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroPedido(RegistroPedido other) : this() {
      id_ = other.id_;
      dataEntrada_ = other.dataEntrada_;
      dataEntrega_ = other.dataEntrega_;
      endereco_ = other.endereco_;
      telefone_ = other.telefone_;
      email_ = other.email_;
      observacao_ = other.observacao_;
      cliente_ = other.cliente_;
      itens_ = other.itens_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroPedido Clone() {
      return new RegistroPedido(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "dataEntrada" field.</summary>
    public const int DataEntradaFieldNumber = 2;
    private string dataEntrada_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DataEntrada {
      get { return dataEntrada_; }
      set {
        dataEntrada_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "dataEntrega" field.</summary>
    public const int DataEntregaFieldNumber = 3;
    private string dataEntrega_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DataEntrega {
      get { return dataEntrega_; }
      set {
        dataEntrega_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "endereco" field.</summary>
    public const int EnderecoFieldNumber = 4;
    private string endereco_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Endereco {
      get { return endereco_; }
      set {
        endereco_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "telefone" field.</summary>
    public const int TelefoneFieldNumber = 5;
    private string telefone_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Telefone {
      get { return telefone_; }
      set {
        telefone_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "email" field.</summary>
    public const int EmailFieldNumber = 6;
    private string email_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Email {
      get { return email_; }
      set {
        email_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "observacao" field.</summary>
    public const int ObservacaoFieldNumber = 7;
    private string observacao_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Observacao {
      get { return observacao_; }
      set {
        observacao_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cliente" field.</summary>
    public const int ClienteFieldNumber = 8;
    private string cliente_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Cliente {
      get { return cliente_; }
      set {
        cliente_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "itens" field.</summary>
    public const int ItensFieldNumber = 9;
    private static readonly pb::FieldCodec<global::ServidorPedidos.ProdutoItem> _repeated_itens_codec
        = pb::FieldCodec.ForMessage(74, global::ServidorPedidos.ProdutoItem.Parser);
    private readonly pbc::RepeatedField<global::ServidorPedidos.ProdutoItem> itens_ = new pbc::RepeatedField<global::ServidorPedidos.ProdutoItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ServidorPedidos.ProdutoItem> Itens {
      get { return itens_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegistroPedido);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegistroPedido other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (DataEntrada != other.DataEntrada) return false;
      if (DataEntrega != other.DataEntrega) return false;
      if (Endereco != other.Endereco) return false;
      if (Telefone != other.Telefone) return false;
      if (Email != other.Email) return false;
      if (Observacao != other.Observacao) return false;
      if (Cliente != other.Cliente) return false;
      if(!itens_.Equals(other.itens_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (DataEntrada.Length != 0) hash ^= DataEntrada.GetHashCode();
      if (DataEntrega.Length != 0) hash ^= DataEntrega.GetHashCode();
      if (Endereco.Length != 0) hash ^= Endereco.GetHashCode();
      if (Telefone.Length != 0) hash ^= Telefone.GetHashCode();
      if (Email.Length != 0) hash ^= Email.GetHashCode();
      if (Observacao.Length != 0) hash ^= Observacao.GetHashCode();
      if (Cliente.Length != 0) hash ^= Cliente.GetHashCode();
      hash ^= itens_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (DataEntrada.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(DataEntrada);
      }
      if (DataEntrega.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(DataEntrega);
      }
      if (Endereco.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Endereco);
      }
      if (Telefone.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Telefone);
      }
      if (Email.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Email);
      }
      if (Observacao.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Observacao);
      }
      if (Cliente.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(Cliente);
      }
      itens_.WriteTo(output, _repeated_itens_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (DataEntrada.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DataEntrada);
      }
      if (DataEntrega.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DataEntrega);
      }
      if (Endereco.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Endereco);
      }
      if (Telefone.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Telefone);
      }
      if (Email.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Email);
      }
      if (Observacao.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Observacao);
      }
      if (Cliente.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Cliente);
      }
      size += itens_.CalculateSize(_repeated_itens_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegistroPedido other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.DataEntrada.Length != 0) {
        DataEntrada = other.DataEntrada;
      }
      if (other.DataEntrega.Length != 0) {
        DataEntrega = other.DataEntrega;
      }
      if (other.Endereco.Length != 0) {
        Endereco = other.Endereco;
      }
      if (other.Telefone.Length != 0) {
        Telefone = other.Telefone;
      }
      if (other.Email.Length != 0) {
        Email = other.Email;
      }
      if (other.Observacao.Length != 0) {
        Observacao = other.Observacao;
      }
      if (other.Cliente.Length != 0) {
        Cliente = other.Cliente;
      }
      itens_.Add(other.itens_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            DataEntrada = input.ReadString();
            break;
          }
          case 26: {
            DataEntrega = input.ReadString();
            break;
          }
          case 34: {
            Endereco = input.ReadString();
            break;
          }
          case 42: {
            Telefone = input.ReadString();
            break;
          }
          case 50: {
            Email = input.ReadString();
            break;
          }
          case 58: {
            Observacao = input.ReadString();
            break;
          }
          case 66: {
            Cliente = input.ReadString();
            break;
          }
          case 74: {
            itens_.AddEntriesFrom(input, _repeated_itens_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class PedidoResponse : pb::IMessage<PedidoResponse> {
    private static readonly pb::MessageParser<PedidoResponse> _parser = new pb::MessageParser<PedidoResponse>(() => new PedidoResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PedidoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorPedidos.ServidorPedidosReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PedidoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PedidoResponse(PedidoResponse other) : this() {
      pedido_ = other.pedido_ != null ? other.pedido_.Clone() : null;
      message_ = other.message_;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PedidoResponse Clone() {
      return new PedidoResponse(this);
    }

    /// <summary>Field number for the "pedido" field.</summary>
    public const int PedidoFieldNumber = 1;
    private global::ServidorPedidos.RegistroPedido pedido_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorPedidos.RegistroPedido Pedido {
      get { return pedido_; }
      set {
        pedido_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 3;
    private int error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PedidoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PedidoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Pedido, other.Pedido)) return false;
      if (Message != other.Message) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (pedido_ != null) hash ^= Pedido.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Error != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (pedido_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Pedido);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Error != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (pedido_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pedido);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Error != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PedidoResponse other) {
      if (other == null) {
        return;
      }
      if (other.pedido_ != null) {
        if (pedido_ == null) {
          pedido_ = new global::ServidorPedidos.RegistroPedido();
        }
        Pedido.MergeFrom(other.Pedido);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Error != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (pedido_ == null) {
              pedido_ = new global::ServidorPedidos.RegistroPedido();
            }
            input.ReadMessage(pedido_);
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            Error = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ModoBusca : pb::IMessage<ModoBusca> {
    private static readonly pb::MessageParser<ModoBusca> _parser = new pb::MessageParser<ModoBusca>(() => new ModoBusca());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ModoBusca> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorPedidos.ServidorPedidosReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca(ModoBusca other) : this() {
      tipo_ = other.tipo_;
      id_ = other.id_;
      nome_ = other.nome_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca Clone() {
      return new ModoBusca(this);
    }

    /// <summary>Field number for the "tipo" field.</summary>
    public const int TipoFieldNumber = 1;
    private global::ServidorPedidos.ModoBusca.Types.Modo tipo_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorPedidos.ModoBusca.Types.Modo Tipo {
      get { return tipo_; }
      set {
        tipo_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nome" field.</summary>
    public const int NomeFieldNumber = 3;
    private string nome_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nome {
      get { return nome_; }
      set {
        nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ModoBusca);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ModoBusca other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Tipo != other.Tipo) return false;
      if (Id != other.Id) return false;
      if (Nome != other.Nome) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Tipo != 0) hash ^= Tipo.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Nome.Length != 0) hash ^= Nome.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Tipo != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Tipo);
      }
      if (Id != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Id);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nome);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Tipo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Tipo);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Nome.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ModoBusca other) {
      if (other == null) {
        return;
      }
      if (other.Tipo != 0) {
        Tipo = other.Tipo;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Nome.Length != 0) {
        Nome = other.Nome;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            tipo_ = (global::ServidorPedidos.ModoBusca.Types.Modo) input.ReadEnum();
            break;
          }
          case 16: {
            Id = input.ReadInt32();
            break;
          }
          case 26: {
            Nome = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ModoBusca message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Modo {
        [pbr::OriginalName("NOME")] Nome = 0,
        [pbr::OriginalName("ID")] Id = 1,
        [pbr::OriginalName("TODOS")] Todos = 2,
      }

    }
    #endregion

  }

  public sealed partial class Resultado : pb::IMessage<Resultado> {
    private static readonly pb::MessageParser<Resultado> _parser = new pb::MessageParser<Resultado>(() => new Resultado());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resultado> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorPedidos.ServidorPedidosReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado(Resultado other) : this() {
      pedidos_ = other.pedidos_.Clone();
      response_ = other.response_ != null ? other.response_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado Clone() {
      return new Resultado(this);
    }

    /// <summary>Field number for the "pedidos" field.</summary>
    public const int PedidosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ServidorPedidos.RegistroPedido> _repeated_pedidos_codec
        = pb::FieldCodec.ForMessage(10, global::ServidorPedidos.RegistroPedido.Parser);
    private readonly pbc::RepeatedField<global::ServidorPedidos.RegistroPedido> pedidos_ = new pbc::RepeatedField<global::ServidorPedidos.RegistroPedido>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ServidorPedidos.RegistroPedido> Pedidos {
      get { return pedidos_; }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 2;
    private global::ServidorPedidos.PedidoResponse response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorPedidos.PedidoResponse Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resultado);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resultado other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pedidos_.Equals(other.pedidos_)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pedidos_.GetHashCode();
      if (response_ != null) hash ^= Response.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      pedidos_.WriteTo(output, _repeated_pedidos_codec);
      if (response_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += pedidos_.CalculateSize(_repeated_pedidos_codec);
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resultado other) {
      if (other == null) {
        return;
      }
      pedidos_.Add(other.pedidos_);
      if (other.response_ != null) {
        if (response_ == null) {
          response_ = new global::ServidorPedidos.PedidoResponse();
        }
        Response.MergeFrom(other.Response);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            pedidos_.AddEntriesFrom(input, _repeated_pedidos_codec);
            break;
          }
          case 18: {
            if (response_ == null) {
              response_ = new global::ServidorPedidos.PedidoResponse();
            }
            input.ReadMessage(response_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
