// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServidorProdutos.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ServidorProdutos {

  /// <summary>Holder for reflection information generated from ServidorProdutos.proto</summary>
  public static partial class ServidorProdutosReflection {

    #region Descriptor
    /// <summary>File descriptor for ServidorProdutos.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServidorProdutosReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChZTZXJ2aWRvclByb2R1dG9zLnByb3RvEhBTZXJ2aWRvclByb2R1dG9zIlcK",
            "D1JlZ2lzdHJvUHJvZHV0bxIKCgJpZBgBIAEoBRIMCgRub21lGAIgASgJEhQK",
            "DHByZWNvVW5pZGFkZRgDIAEoARIUCgxkYXRhQ2FkYXN0cm8YBCABKAkiZwoP",
            "UHJvZHV0b1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkSNAoJcnByb2R1dG9y",
            "GAIgASgLMiEuU2Vydmlkb3JQcm9kdXRvcy5SZWdpc3Ryb1Byb2R1dG8SDQoF",
            "ZXJyb3IYAyABKAUiegoJTW9kb0J1c2NhEi4KBHRpcG8YASABKA4yIC5TZXJ2",
            "aWRvclByb2R1dG9zLk1vZG9CdXNjYS5Nb2RvEgoKAmlkGAIgASgFEgwKBG5v",
            "bWUYAyABKAkiIwoETW9kbxIICgROT01FEAASBgoCSUQQARIJCgVUT0RPUxAC",
            "InUKCVJlc3VsdGFkbxIzCghwcm9kdXRvcxgBIAMoCzIhLlNlcnZpZG9yUHJv",
            "ZHV0b3MuUmVnaXN0cm9Qcm9kdXRvEjMKCHJlc3BvbnNlGAIgASgLMiEuU2Vy",
            "dmlkb3JQcm9kdXRvcy5Qcm9kdXRvUmVzcG9uc2Uy9QEKCFByb2R1dG9zElAK",
            "BlNhbHZhchIhLlNlcnZpZG9yUHJvZHV0b3MuUmVnaXN0cm9Qcm9kdXRvGiEu",
            "U2Vydmlkb3JQcm9kdXRvcy5Qcm9kdXRvUmVzcG9uc2UiABJECgZCdXNjYXIS",
            "Gy5TZXJ2aWRvclByb2R1dG9zLk1vZG9CdXNjYRobLlNlcnZpZG9yUHJvZHV0",
            "b3MuUmVzdWx0YWRvIgASUQoHRXhjbHVpchIhLlNlcnZpZG9yUHJvZHV0b3Mu",
            "UmVnaXN0cm9Qcm9kdXRvGiEuU2Vydmlkb3JQcm9kdXRvcy5Qcm9kdXRvUmVz",
            "cG9uc2UiAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorProdutos.RegistroProduto), global::ServidorProdutos.RegistroProduto.Parser, new[]{ "Id", "Nome", "PrecoUnidade", "DataCadastro" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorProdutos.ProdutoResponse), global::ServidorProdutos.ProdutoResponse.Parser, new[]{ "Message", "Rprodutor", "Error" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorProdutos.ModoBusca), global::ServidorProdutos.ModoBusca.Parser, new[]{ "Tipo", "Id", "Nome" }, null, new[]{ typeof(global::ServidorProdutos.ModoBusca.Types.Modo) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorProdutos.Resultado), global::ServidorProdutos.Resultado.Parser, new[]{ "Produtos", "Response" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RegistroProduto : pb::IMessage<RegistroProduto> {
    private static readonly pb::MessageParser<RegistroProduto> _parser = new pb::MessageParser<RegistroProduto>(() => new RegistroProduto());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegistroProduto> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorProdutos.ServidorProdutosReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroProduto() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroProduto(RegistroProduto other) : this() {
      id_ = other.id_;
      nome_ = other.nome_;
      precoUnidade_ = other.precoUnidade_;
      dataCadastro_ = other.dataCadastro_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegistroProduto Clone() {
      return new RegistroProduto(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nome" field.</summary>
    public const int NomeFieldNumber = 2;
    private string nome_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nome {
      get { return nome_; }
      set {
        nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "precoUnidade" field.</summary>
    public const int PrecoUnidadeFieldNumber = 3;
    private double precoUnidade_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double PrecoUnidade {
      get { return precoUnidade_; }
      set {
        precoUnidade_ = value;
      }
    }

    /// <summary>Field number for the "dataCadastro" field.</summary>
    public const int DataCadastroFieldNumber = 4;
    private string dataCadastro_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DataCadastro {
      get { return dataCadastro_; }
      set {
        dataCadastro_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegistroProduto);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegistroProduto other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Nome != other.Nome) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(PrecoUnidade, other.PrecoUnidade)) return false;
      if (DataCadastro != other.DataCadastro) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Nome.Length != 0) hash ^= Nome.GetHashCode();
      if (PrecoUnidade != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(PrecoUnidade);
      if (DataCadastro.Length != 0) hash ^= DataCadastro.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Id);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Nome);
      }
      if (PrecoUnidade != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(PrecoUnidade);
      }
      if (DataCadastro.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(DataCadastro);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Nome.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
      }
      if (PrecoUnidade != 0D) {
        size += 1 + 8;
      }
      if (DataCadastro.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DataCadastro);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegistroProduto other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Nome.Length != 0) {
        Nome = other.Nome;
      }
      if (other.PrecoUnidade != 0D) {
        PrecoUnidade = other.PrecoUnidade;
      }
      if (other.DataCadastro.Length != 0) {
        DataCadastro = other.DataCadastro;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt32();
            break;
          }
          case 18: {
            Nome = input.ReadString();
            break;
          }
          case 25: {
            PrecoUnidade = input.ReadDouble();
            break;
          }
          case 34: {
            DataCadastro = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ProdutoResponse : pb::IMessage<ProdutoResponse> {
    private static readonly pb::MessageParser<ProdutoResponse> _parser = new pb::MessageParser<ProdutoResponse>(() => new ProdutoResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ProdutoResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorProdutos.ServidorProdutosReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProdutoResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProdutoResponse(ProdutoResponse other) : this() {
      message_ = other.message_;
      rprodutor_ = other.rprodutor_ != null ? other.rprodutor_.Clone() : null;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ProdutoResponse Clone() {
      return new ProdutoResponse(this);
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 1;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "rprodutor" field.</summary>
    public const int RprodutorFieldNumber = 2;
    private global::ServidorProdutos.RegistroProduto rprodutor_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorProdutos.RegistroProduto Rprodutor {
      get { return rprodutor_; }
      set {
        rprodutor_ = value;
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 3;
    private int error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ProdutoResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ProdutoResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Message != other.Message) return false;
      if (!object.Equals(Rprodutor, other.Rprodutor)) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (rprodutor_ != null) hash ^= Rprodutor.GetHashCode();
      if (Error != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Message.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Message);
      }
      if (rprodutor_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Rprodutor);
      }
      if (Error != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (rprodutor_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rprodutor);
      }
      if (Error != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ProdutoResponse other) {
      if (other == null) {
        return;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.rprodutor_ != null) {
        if (rprodutor_ == null) {
          rprodutor_ = new global::ServidorProdutos.RegistroProduto();
        }
        Rprodutor.MergeFrom(other.Rprodutor);
      }
      if (other.Error != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Message = input.ReadString();
            break;
          }
          case 18: {
            if (rprodutor_ == null) {
              rprodutor_ = new global::ServidorProdutos.RegistroProduto();
            }
            input.ReadMessage(rprodutor_);
            break;
          }
          case 24: {
            Error = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ModoBusca : pb::IMessage<ModoBusca> {
    private static readonly pb::MessageParser<ModoBusca> _parser = new pb::MessageParser<ModoBusca>(() => new ModoBusca());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ModoBusca> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorProdutos.ServidorProdutosReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca(ModoBusca other) : this() {
      tipo_ = other.tipo_;
      id_ = other.id_;
      nome_ = other.nome_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ModoBusca Clone() {
      return new ModoBusca(this);
    }

    /// <summary>Field number for the "tipo" field.</summary>
    public const int TipoFieldNumber = 1;
    private global::ServidorProdutos.ModoBusca.Types.Modo tipo_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorProdutos.ModoBusca.Types.Modo Tipo {
      get { return tipo_; }
      set {
        tipo_ = value;
      }
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 2;
    private int id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "nome" field.</summary>
    public const int NomeFieldNumber = 3;
    private string nome_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Nome {
      get { return nome_; }
      set {
        nome_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ModoBusca);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ModoBusca other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Tipo != other.Tipo) return false;
      if (Id != other.Id) return false;
      if (Nome != other.Nome) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Tipo != 0) hash ^= Tipo.GetHashCode();
      if (Id != 0) hash ^= Id.GetHashCode();
      if (Nome.Length != 0) hash ^= Nome.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Tipo != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Tipo);
      }
      if (Id != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Id);
      }
      if (Nome.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Nome);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Tipo != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Tipo);
      }
      if (Id != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Id);
      }
      if (Nome.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Nome);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ModoBusca other) {
      if (other == null) {
        return;
      }
      if (other.Tipo != 0) {
        Tipo = other.Tipo;
      }
      if (other.Id != 0) {
        Id = other.Id;
      }
      if (other.Nome.Length != 0) {
        Nome = other.Nome;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            tipo_ = (global::ServidorProdutos.ModoBusca.Types.Modo) input.ReadEnum();
            break;
          }
          case 16: {
            Id = input.ReadInt32();
            break;
          }
          case 26: {
            Nome = input.ReadString();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the ModoBusca message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Modo {
        [pbr::OriginalName("NOME")] Nome = 0,
        [pbr::OriginalName("ID")] Id = 1,
        [pbr::OriginalName("TODOS")] Todos = 2,
      }

    }
    #endregion

  }

  public sealed partial class Resultado : pb::IMessage<Resultado> {
    private static readonly pb::MessageParser<Resultado> _parser = new pb::MessageParser<Resultado>(() => new Resultado());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resultado> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorProdutos.ServidorProdutosReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado(Resultado other) : this() {
      produtos_ = other.produtos_.Clone();
      response_ = other.response_ != null ? other.response_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resultado Clone() {
      return new Resultado(this);
    }

    /// <summary>Field number for the "produtos" field.</summary>
    public const int ProdutosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ServidorProdutos.RegistroProduto> _repeated_produtos_codec
        = pb::FieldCodec.ForMessage(10, global::ServidorProdutos.RegistroProduto.Parser);
    private readonly pbc::RepeatedField<global::ServidorProdutos.RegistroProduto> produtos_ = new pbc::RepeatedField<global::ServidorProdutos.RegistroProduto>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ServidorProdutos.RegistroProduto> Produtos {
      get { return produtos_; }
    }

    /// <summary>Field number for the "response" field.</summary>
    public const int ResponseFieldNumber = 2;
    private global::ServidorProdutos.ProdutoResponse response_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorProdutos.ProdutoResponse Response {
      get { return response_; }
      set {
        response_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resultado);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resultado other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!produtos_.Equals(other.produtos_)) return false;
      if (!object.Equals(Response, other.Response)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= produtos_.GetHashCode();
      if (response_ != null) hash ^= Response.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      produtos_.WriteTo(output, _repeated_produtos_codec);
      if (response_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Response);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += produtos_.CalculateSize(_repeated_produtos_codec);
      if (response_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Response);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resultado other) {
      if (other == null) {
        return;
      }
      produtos_.Add(other.produtos_);
      if (other.response_ != null) {
        if (response_ == null) {
          response_ = new global::ServidorProdutos.ProdutoResponse();
        }
        Response.MergeFrom(other.Response);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            produtos_.AddEntriesFrom(input, _repeated_produtos_codec);
            break;
          }
          case 18: {
            if (response_ == null) {
              response_ = new global::ServidorProdutos.ProdutoResponse();
            }
            input.ReadMessage(response_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
