// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ServidorAutenticacao.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ServidorAutenticacao {

  /// <summary>Holder for reflection information generated from ServidorAutenticacao.proto</summary>
  public static partial class ServidorAutenticacaoReflection {

    #region Descriptor
    /// <summary>File descriptor for ServidorAutenticacao.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ServidorAutenticacaoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChpTZXJ2aWRvckF1dGVudGljYWNhby5wcm90bxIUU2Vydmlkb3JBdXRlbnRp",
            "Y2FjYW8aFlNlcnZpZG9yVXN1YXJpb3MucHJvdG8iYgoLQXV0UmVzcG9uc2US",
            "MwoIcnVzdWFyaW8YASABKAsyIS5TZXJ2aWRvclVzdWFyaW9zLlJlZ2lzdHJv",
            "VXN1YXJpbxIPCgdtZXNzYWdlGAIgASgJEg0KBWVycm9yGAMgASgFMmQKDEF1",
            "dGVudGljYWNhbxJUCgpBdXRlbnRpY2FyEiEuU2Vydmlkb3JVc3Vhcmlvcy5S",
            "ZWdpc3Ryb1VzdWFyaW8aIS5TZXJ2aWRvckF1dGVudGljYWNhby5BdXRSZXNw",
            "b25zZSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::ServidorUsuarios.ServidorUsuariosReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ServidorAutenticacao.AutResponse), global::ServidorAutenticacao.AutResponse.Parser, new[]{ "Rusuario", "Message", "Error" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AutResponse : pb::IMessage<AutResponse> {
    private static readonly pb::MessageParser<AutResponse> _parser = new pb::MessageParser<AutResponse>(() => new AutResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AutResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ServidorAutenticacao.ServidorAutenticacaoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AutResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AutResponse(AutResponse other) : this() {
      rusuario_ = other.rusuario_ != null ? other.rusuario_.Clone() : null;
      message_ = other.message_;
      error_ = other.error_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AutResponse Clone() {
      return new AutResponse(this);
    }

    /// <summary>Field number for the "rusuario" field.</summary>
    public const int RusuarioFieldNumber = 1;
    private global::ServidorUsuarios.RegistroUsuario rusuario_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::ServidorUsuarios.RegistroUsuario Rusuario {
      get { return rusuario_; }
      set {
        rusuario_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "error" field.</summary>
    public const int ErrorFieldNumber = 3;
    private int error_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Error {
      get { return error_; }
      set {
        error_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AutResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AutResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Rusuario, other.Rusuario)) return false;
      if (Message != other.Message) return false;
      if (Error != other.Error) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (rusuario_ != null) hash ^= Rusuario.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Error != 0) hash ^= Error.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (rusuario_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Rusuario);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Error != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Error);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (rusuario_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Rusuario);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Error != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Error);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AutResponse other) {
      if (other == null) {
        return;
      }
      if (other.rusuario_ != null) {
        if (rusuario_ == null) {
          rusuario_ = new global::ServidorUsuarios.RegistroUsuario();
        }
        Rusuario.MergeFrom(other.Rusuario);
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Error != 0) {
        Error = other.Error;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (rusuario_ == null) {
              rusuario_ = new global::ServidorUsuarios.RegistroUsuario();
            }
            input.ReadMessage(rusuario_);
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            Error = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
