// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ServidorNomes.proto

/*
Package ServidorNomes is a generated protocol buffer package.

It is generated from these files:
	ServidorNomes.proto

It has these top-level messages:
	RegistroServico
	ServicoResponse
	Relatorio
	ServicoRequest
*/
package ServidorNomes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RegistroServico struct {
	Host    string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Porta   int32  `protobuf:"varint,2,opt,name=porta" json:"porta,omitempty"`
	Servico string `protobuf:"bytes,3,opt,name=servico" json:"servico,omitempty"`
}

func (m *RegistroServico) Reset()                    { *m = RegistroServico{} }
func (m *RegistroServico) String() string            { return proto.CompactTextString(m) }
func (*RegistroServico) ProtoMessage()               {}
func (*RegistroServico) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegistroServico) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *RegistroServico) GetPorta() int32 {
	if m != nil {
		return m.Porta
	}
	return 0
}

func (m *RegistroServico) GetServico() string {
	if m != nil {
		return m.Servico
	}
	return ""
}

type ServicoResponse struct {
	Servico *RegistroServico `protobuf:"bytes,1,opt,name=servico" json:"servico,omitempty"`
	Message string           `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Error   int32            `protobuf:"varint,3,opt,name=error" json:"error,omitempty"`
}

func (m *ServicoResponse) Reset()                    { *m = ServicoResponse{} }
func (m *ServicoResponse) String() string            { return proto.CompactTextString(m) }
func (*ServicoResponse) ProtoMessage()               {}
func (*ServicoResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ServicoResponse) GetServico() *RegistroServico {
	if m != nil {
		return m.Servico
	}
	return nil
}

func (m *ServicoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ServicoResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type Relatorio struct {
	Host                 string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	NumeroConexoesAtivas int32  `protobuf:"varint,2,opt,name=NumeroConexoesAtivas" json:"NumeroConexoesAtivas,omitempty"`
}

func (m *Relatorio) Reset()                    { *m = Relatorio{} }
func (m *Relatorio) String() string            { return proto.CompactTextString(m) }
func (*Relatorio) ProtoMessage()               {}
func (*Relatorio) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Relatorio) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Relatorio) GetNumeroConexoesAtivas() int32 {
	if m != nil {
		return m.NumeroConexoesAtivas
	}
	return 0
}

type ServicoRequest struct {
	Servico string `protobuf:"bytes,1,opt,name=servico" json:"servico,omitempty"`
}

func (m *ServicoRequest) Reset()                    { *m = ServicoRequest{} }
func (m *ServicoRequest) String() string            { return proto.CompactTextString(m) }
func (*ServicoRequest) ProtoMessage()               {}
func (*ServicoRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ServicoRequest) GetServico() string {
	if m != nil {
		return m.Servico
	}
	return ""
}

func init() {
	proto.RegisterType((*RegistroServico)(nil), "ServidorNomes.RegistroServico")
	proto.RegisterType((*ServicoResponse)(nil), "ServidorNomes.ServicoResponse")
	proto.RegisterType((*Relatorio)(nil), "ServidorNomes.Relatorio")
	proto.RegisterType((*ServicoRequest)(nil), "ServidorNomes.ServicoRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Nomes service

type NomesClient interface {
	Cadastrar(ctx context.Context, in *RegistroServico, opts ...grpc.CallOption) (*ServicoResponse, error)
	ObterServico(ctx context.Context, in *ServicoRequest, opts ...grpc.CallOption) (*ServicoResponse, error)
}

type nomesClient struct {
	cc *grpc.ClientConn
}

func NewNomesClient(cc *grpc.ClientConn) NomesClient {
	return &nomesClient{cc}
}

func (c *nomesClient) Cadastrar(ctx context.Context, in *RegistroServico, opts ...grpc.CallOption) (*ServicoResponse, error) {
	out := new(ServicoResponse)
	err := grpc.Invoke(ctx, "/ServidorNomes.Nomes/Cadastrar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nomesClient) ObterServico(ctx context.Context, in *ServicoRequest, opts ...grpc.CallOption) (*ServicoResponse, error) {
	out := new(ServicoResponse)
	err := grpc.Invoke(ctx, "/ServidorNomes.Nomes/ObterServico", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Nomes service

type NomesServer interface {
	Cadastrar(context.Context, *RegistroServico) (*ServicoResponse, error)
	ObterServico(context.Context, *ServicoRequest) (*ServicoResponse, error)
}

func RegisterNomesServer(s *grpc.Server, srv NomesServer) {
	s.RegisterService(&_Nomes_serviceDesc, srv)
}

func _Nomes_Cadastrar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistroServico)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomesServer).Cadastrar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServidorNomes.Nomes/Cadastrar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomesServer).Cadastrar(ctx, req.(*RegistroServico))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nomes_ObterServico_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServicoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NomesServer).ObterServico(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServidorNomes.Nomes/ObterServico",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NomesServer).ObterServico(ctx, req.(*ServicoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Nomes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ServidorNomes.Nomes",
	HandlerType: (*NomesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cadastrar",
			Handler:    _Nomes_Cadastrar_Handler,
		},
		{
			MethodName: "ObterServico",
			Handler:    _Nomes_ObterServico_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ServidorNomes.proto",
}

func init() { proto.RegisterFile("ServidorNomes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x5d, 0x35, 0x4a, 0xc6, 0x3f, 0x85, 0xb5, 0x87, 0x20, 0x28, 0x65, 0x4f, 0xc5, 0x43,
	0x0f, 0xf1, 0xe2, 0x55, 0x7a, 0xb6, 0x85, 0x2d, 0x3e, 0xc0, 0xd6, 0x0e, 0x35, 0x60, 0x3a, 0x71,
	0x66, 0x5b, 0x04, 0x1f, 0xc8, 0xd7, 0x94, 0x6c, 0x9a, 0x6a, 0x42, 0x4b, 0x6e, 0xf9, 0x32, 0x33,
	0xdf, 0x7c, 0xbf, 0xdd, 0x85, 0x9b, 0x19, 0xf2, 0x26, 0x5b, 0x10, 0x4f, 0x28, 0x47, 0x19, 0x15,
	0x4c, 0x9e, 0xf4, 0x55, 0xe3, 0xa7, 0x79, 0x85, 0x9e, 0xc5, 0x65, 0x26, 0x9e, 0x29, 0x14, 0xde,
	0x48, 0x6b, 0x38, 0x7d, 0x27, 0xf1, 0x89, 0x1a, 0xa8, 0x61, 0x6c, 0xc3, 0xb7, 0xee, 0x43, 0x54,
	0x10, 0x7b, 0x97, 0x1c, 0x0f, 0xd4, 0x30, 0xb2, 0x95, 0xd0, 0x09, 0x9c, 0x4b, 0x35, 0x94, 0x9c,
	0x84, 0xe6, 0x5a, 0x9a, 0x6f, 0xe8, 0x6d, 0xed, 0x2c, 0x4a, 0x41, 0x2b, 0x41, 0xfd, 0xf4, 0xd7,
	0x5c, 0x3a, 0x5f, 0xa4, 0xf7, 0xa3, 0x66, 0xbe, 0x56, 0x8e, 0x9d, 0x59, 0xb9, 0x26, 0x47, 0x11,
	0xb7, 0xc4, 0xb0, 0x3e, 0xb6, 0xb5, 0x2c, 0x63, 0x21, 0x33, 0x71, 0x58, 0x1f, 0xd9, 0x4a, 0x98,
	0x19, 0xc4, 0x16, 0x3f, 0x9c, 0x27, 0xce, 0xf6, 0xd3, 0xa4, 0xd0, 0x9f, 0xac, 0x73, 0x64, 0x1a,
	0xd3, 0x0a, 0xbf, 0x08, 0xe5, 0xd9, 0x67, 0x1b, 0x27, 0x5b, 0xb8, 0xbd, 0x35, 0xf3, 0x00, 0xd7,
	0x3b, 0xa2, 0xcf, 0x35, 0x8a, 0xff, 0x4f, 0xaf, 0x1a, 0xf4, 0xe9, 0x8f, 0x82, 0x28, 0x30, 0xe9,
	0x17, 0x88, 0xc7, 0x6e, 0xe1, 0xc4, 0xb3, 0x63, 0xdd, 0x01, 0x7c, 0xdb, 0xae, 0xb7, 0x4e, 0xd0,
	0x1c, 0xe9, 0x29, 0x5c, 0x4e, 0xe7, 0x1e, 0xb9, 0xbe, 0xaa, 0xbb, 0x43, 0x13, 0x21, 0x61, 0xb7,
	0xe1, 0xfc, 0x2c, 0x3c, 0x8a, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7c, 0xe4, 0x80, 0x97,
	0x2b, 0x02, 0x00, 0x00,
}
