// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ServidorClientes.proto

/*
Package ServidorClientes is a generated protocol buffer package.

It is generated from these files:
	ServidorClientes.proto

It has these top-level messages:
	RegistroCliente
	ClienteResponse
	ModoBusca
	Resultado
*/
package ServidorClientes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ModoBusca_Modo int32

const (
	ModoBusca_NOME  ModoBusca_Modo = 0
	ModoBusca_ID    ModoBusca_Modo = 1
	ModoBusca_TODOS ModoBusca_Modo = 2
)

var ModoBusca_Modo_name = map[int32]string{
	0: "NOME",
	1: "ID",
	2: "TODOS",
}
var ModoBusca_Modo_value = map[string]int32{
	"NOME":  0,
	"ID":    1,
	"TODOS": 2,
}

func (x ModoBusca_Modo) String() string {
	return proto.EnumName(ModoBusca_Modo_name, int32(x))
}
func (ModoBusca_Modo) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

type RegistroCliente struct {
	Id           int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Nome         string `protobuf:"bytes,2,opt,name=nome" json:"nome,omitempty"`
	Email        string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Telefone     string `protobuf:"bytes,4,opt,name=telefone" json:"telefone,omitempty"`
	DataCadastro string `protobuf:"bytes,5,opt,name=dataCadastro" json:"dataCadastro,omitempty"`
}

func (m *RegistroCliente) Reset()                    { *m = RegistroCliente{} }
func (m *RegistroCliente) String() string            { return proto.CompactTextString(m) }
func (*RegistroCliente) ProtoMessage()               {}
func (*RegistroCliente) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RegistroCliente) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegistroCliente) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

func (m *RegistroCliente) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegistroCliente) GetTelefone() string {
	if m != nil {
		return m.Telefone
	}
	return ""
}

func (m *RegistroCliente) GetDataCadastro() string {
	if m != nil {
		return m.DataCadastro
	}
	return ""
}

type ClienteResponse struct {
	Message  string           `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	Rcliente *RegistroCliente `protobuf:"bytes,2,opt,name=rcliente" json:"rcliente,omitempty"`
	Error    int32            `protobuf:"varint,3,opt,name=error" json:"error,omitempty"`
}

func (m *ClienteResponse) Reset()                    { *m = ClienteResponse{} }
func (m *ClienteResponse) String() string            { return proto.CompactTextString(m) }
func (*ClienteResponse) ProtoMessage()               {}
func (*ClienteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClienteResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *ClienteResponse) GetRcliente() *RegistroCliente {
	if m != nil {
		return m.Rcliente
	}
	return nil
}

func (m *ClienteResponse) GetError() int32 {
	if m != nil {
		return m.Error
	}
	return 0
}

type ModoBusca struct {
	Tipo ModoBusca_Modo `protobuf:"varint,1,opt,name=tipo,enum=ServidorClientes.ModoBusca_Modo" json:"tipo,omitempty"`
	Id   int32          `protobuf:"varint,2,opt,name=id" json:"id,omitempty"`
	Nome string         `protobuf:"bytes,3,opt,name=nome" json:"nome,omitempty"`
}

func (m *ModoBusca) Reset()                    { *m = ModoBusca{} }
func (m *ModoBusca) String() string            { return proto.CompactTextString(m) }
func (*ModoBusca) ProtoMessage()               {}
func (*ModoBusca) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ModoBusca) GetTipo() ModoBusca_Modo {
	if m != nil {
		return m.Tipo
	}
	return ModoBusca_NOME
}

func (m *ModoBusca) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ModoBusca) GetNome() string {
	if m != nil {
		return m.Nome
	}
	return ""
}

type Resultado struct {
	Clientes []*RegistroCliente `protobuf:"bytes,1,rep,name=clientes" json:"clientes,omitempty"`
	Message  *ClienteResponse   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *Resultado) Reset()                    { *m = Resultado{} }
func (m *Resultado) String() string            { return proto.CompactTextString(m) }
func (*Resultado) ProtoMessage()               {}
func (*Resultado) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Resultado) GetClientes() []*RegistroCliente {
	if m != nil {
		return m.Clientes
	}
	return nil
}

func (m *Resultado) GetMessage() *ClienteResponse {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*RegistroCliente)(nil), "ServidorClientes.RegistroCliente")
	proto.RegisterType((*ClienteResponse)(nil), "ServidorClientes.ClienteResponse")
	proto.RegisterType((*ModoBusca)(nil), "ServidorClientes.ModoBusca")
	proto.RegisterType((*Resultado)(nil), "ServidorClientes.Resultado")
	proto.RegisterEnum("ServidorClientes.ModoBusca_Modo", ModoBusca_Modo_name, ModoBusca_Modo_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Clientes service

type ClientesClient interface {
	Salvar(ctx context.Context, in *RegistroCliente, opts ...grpc.CallOption) (*ClienteResponse, error)
	Buscar(ctx context.Context, in *ModoBusca, opts ...grpc.CallOption) (*Resultado, error)
	Excluir(ctx context.Context, in *RegistroCliente, opts ...grpc.CallOption) (*ClienteResponse, error)
}

type clientesClient struct {
	cc *grpc.ClientConn
}

func NewClientesClient(cc *grpc.ClientConn) ClientesClient {
	return &clientesClient{cc}
}

func (c *clientesClient) Salvar(ctx context.Context, in *RegistroCliente, opts ...grpc.CallOption) (*ClienteResponse, error) {
	out := new(ClienteResponse)
	err := grpc.Invoke(ctx, "/ServidorClientes.Clientes/Salvar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientesClient) Buscar(ctx context.Context, in *ModoBusca, opts ...grpc.CallOption) (*Resultado, error) {
	out := new(Resultado)
	err := grpc.Invoke(ctx, "/ServidorClientes.Clientes/Buscar", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientesClient) Excluir(ctx context.Context, in *RegistroCliente, opts ...grpc.CallOption) (*ClienteResponse, error) {
	out := new(ClienteResponse)
	err := grpc.Invoke(ctx, "/ServidorClientes.Clientes/Excluir", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Clientes service

type ClientesServer interface {
	Salvar(context.Context, *RegistroCliente) (*ClienteResponse, error)
	Buscar(context.Context, *ModoBusca) (*Resultado, error)
	Excluir(context.Context, *RegistroCliente) (*ClienteResponse, error)
}

func RegisterClientesServer(s *grpc.Server, srv ClientesServer) {
	s.RegisterService(&_Clientes_serviceDesc, srv)
}

func _Clientes_Salvar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistroCliente)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientesServer).Salvar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServidorClientes.Clientes/Salvar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientesServer).Salvar(ctx, req.(*RegistroCliente))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clientes_Buscar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModoBusca)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientesServer).Buscar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServidorClientes.Clientes/Buscar",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientesServer).Buscar(ctx, req.(*ModoBusca))
	}
	return interceptor(ctx, in, info, handler)
}

func _Clientes_Excluir_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistroCliente)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientesServer).Excluir(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServidorClientes.Clientes/Excluir",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientesServer).Excluir(ctx, req.(*RegistroCliente))
	}
	return interceptor(ctx, in, info, handler)
}

var _Clientes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ServidorClientes.Clientes",
	HandlerType: (*ClientesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Salvar",
			Handler:    _Clientes_Salvar_Handler,
		},
		{
			MethodName: "Buscar",
			Handler:    _Clientes_Buscar_Handler,
		},
		{
			MethodName: "Excluir",
			Handler:    _Clientes_Excluir_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ServidorClientes.proto",
}

func init() { proto.RegisterFile("ServidorClientes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0x3f, 0x6f, 0xe2, 0x30,
	0x18, 0xc6, 0x71, 0x48, 0x42, 0xf2, 0xde, 0x09, 0xa2, 0x57, 0xa7, 0x53, 0x04, 0x4b, 0xce, 0xb7,
	0x30, 0x31, 0x70, 0xb7, 0x9d, 0x6e, 0x29, 0x30, 0x74, 0xa0, 0xb4, 0xa6, 0x5f, 0xc0, 0x25, 0x2e,
	0xb2, 0x14, 0x62, 0x64, 0x07, 0xd4, 0xb1, 0x5b, 0xa5, 0xf6, 0xf3, 0x76, 0xaf, 0x30, 0x21, 0xa8,
	0xd0, 0x96, 0x0e, 0xdd, 0xfc, 0xfe, 0xcb, 0xf3, 0x3c, 0x3f, 0x29, 0xf0, 0x73, 0x2a, 0xf4, 0x5a,
	0xa6, 0x4a, 0x0f, 0x32, 0x29, 0xf2, 0x42, 0x98, 0xde, 0x52, 0xab, 0x42, 0x61, 0x74, 0xd8, 0xa7,
	0x4f, 0x04, 0x5a, 0x4c, 0xcc, 0xa5, 0x29, 0xb4, 0x2a, 0x9b, 0xd8, 0x04, 0x47, 0xa6, 0x31, 0x49,
	0x48, 0xd7, 0x63, 0x8e, 0x4c, 0x11, 0xc1, 0xcd, 0xd5, 0x42, 0xc4, 0x4e, 0x42, 0xba, 0x21, 0xb3,
	0x6f, 0xfc, 0x01, 0x9e, 0x58, 0x70, 0x99, 0xc5, 0x75, 0xdb, 0xdc, 0x16, 0xd8, 0x86, 0xa0, 0x10,
	0x99, 0xb8, 0x55, 0xb9, 0x88, 0x5d, 0x3b, 0xa8, 0x6a, 0xa4, 0xf0, 0x3d, 0xe5, 0x05, 0x1f, 0xf0,
	0x94, 0x6f, 0xc4, 0x62, 0xcf, 0xce, 0x5f, 0xf5, 0xe8, 0x3d, 0x81, 0x56, 0xe9, 0x82, 0x09, 0xb3,
	0x54, 0xb9, 0x11, 0x18, 0x43, 0x63, 0x21, 0x8c, 0xe1, 0x73, 0x61, 0x2d, 0x85, 0x6c, 0x57, 0xe2,
	0x7f, 0x08, 0xf4, 0x6c, 0xbb, 0x6d, 0xbd, 0x7d, 0xeb, 0xff, 0xea, 0x1d, 0x05, 0x3f, 0x08, 0xc7,
	0xaa, 0x13, 0x1b, 0x41, 0x6b, 0xa5, 0x6d, 0x04, 0x8f, 0x6d, 0x0b, 0xfa, 0x48, 0x20, 0x1c, 0xab,
	0x54, 0x9d, 0xad, 0xcc, 0x8c, 0xe3, 0x5f, 0x70, 0x0b, 0xb9, 0x54, 0x56, 0xb9, 0xd9, 0x4f, 0x8e,
	0x3f, 0x5f, 0xad, 0xda, 0x17, 0xb3, 0xdb, 0x25, 0x40, 0xe7, 0x08, 0x60, 0x7d, 0x0f, 0x90, 0xfe,
	0x06, 0x77, 0x73, 0x81, 0x01, 0xb8, 0x17, 0x93, 0xf1, 0x28, 0xaa, 0xa1, 0x0f, 0xce, 0xf9, 0x30,
	0x22, 0x18, 0x82, 0x77, 0x3d, 0x19, 0x4e, 0xa6, 0x91, 0x43, 0x1f, 0x08, 0x84, 0x4c, 0x98, 0x55,
	0x56, 0xf0, 0x54, 0x6d, 0xf2, 0x96, 0xde, 0x4d, 0x4c, 0x92, 0xfa, 0x27, 0xf3, 0xee, 0x4e, 0xf0,
	0xdf, 0x1e, 0xe4, 0xbb, 0xb4, 0x0e, 0xe0, 0x57, 0xac, 0xfb, 0xcf, 0x04, 0x82, 0xdd, 0x16, 0x5e,
	0x82, 0x3f, 0xe5, 0xd9, 0x9a, 0x6b, 0x3c, 0x6d, 0xa0, 0x7d, 0x5a, 0x85, 0xd6, 0x70, 0x08, 0xbe,
	0xa5, 0xa8, 0xb1, 0xf3, 0x01, 0xe3, 0x76, 0xe7, 0x2d, 0xb9, 0x12, 0x0f, 0xad, 0xe1, 0x15, 0x34,
	0x46, 0x77, 0xb3, 0x6c, 0x25, 0xbf, 0xcc, 0xd8, 0x8d, 0x6f, 0x7f, 0x9c, 0x3f, 0x2f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xb5, 0x9a, 0x45, 0xb5, 0x52, 0x03, 0x00, 0x00,
}
